In [1]:
import pandas as pd
import numpy as np

In [9]:
movies = pd.read_csv('s3://msbx5420-2020/mount massive/')
movies.head()

,titleId,ordering,title,region,language,types,attributes,isOriginalTitle,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres,averageRating,numVotes
0,tt0000001,5,Carmencita,\N,\N,original,\N,1,tt0000001,short,Carmencita,Carmencita,0,1894,\N,1,"Documentary,Short",5.6,1550
1,tt0000003,4,Pauvre Pierrot,\N,\N,original,\N,1,tt0000003,short,Pauvre Pierrot,Pauvre Pierrot,0,1892,\N,4,"Animation,Comedy,Romance",6.5,1207
2,tt0000005,8,Blacksmith Scene,\N,\N,original,\N,1,tt0000005,short,Blacksmith Scene,Blacksmith Scene,0,1893,\N,1,"Comedy,Short",6.1,1934
3,tt0000007,2,Corbett and Courtney Before the Kinetograph,\N,\N,original,\N,1,tt0000007,short,Corbett and Courtney Before the Kinetograph,Corbett and Courtney Before the Kinetograph,0,1894,\N,1,"Short,Sport",5.5,615
4,tt0000008,4,Edison Kinetoscopic Record of a Sneeze,\N,\N,original,\N,1,tt0000008,short,Edison Kinetoscopic Record of a Sneeze,Edison Kinetoscopic Record of a Sneeze,0,1894,\N,1,"Documentary,Short",5.4,1667

In [10]:
movies["WeightedRating"] = np.nan

movies.head()

,titleId,ordering,title,region,language,types,attributes,isOriginalTitle,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres,averageRating,numVotes,WeightedRating
0,tt0000001,5,Carmencita,\N,\N,original,\N,1,tt0000001,short,Carmencita,Carmencita,0,1894,\N,1,"Documentary,Short",5.6,1550,NaN
1,tt0000003,4,Pauvre Pierrot,\N,\N,original,\N,1,tt0000003,short,Pauvre Pierrot,Pauvre Pierrot,0,1892,\N,4,"Animation,Comedy,Romance",6.5,1207,NaN
2,tt0000005,8,Blacksmith Scene,\N,\N,original,\N,1,tt0000005,short,Blacksmith Scene,Blacksmith Scene,0,1893,\N,1,"Comedy,Short",6.1,1934,NaN
3,tt0000007,2,Corbett and Courtney Before the Kinetograph,\N,\N,original,\N,1,tt0000007,short,Corbett and Courtney Before the Kinetograph,Corbett and Courtney Before the Kinetograph,0,1894,\N,1,"Short,Sport",5.5,615,NaN
4,tt0000008,4,Edison Kinetoscopic Record of a Sneeze,\N,\N,original,\N,1,tt0000008,short,Edison Kinetoscopic Record of a Sneeze,Edison Kinetoscopic Record of a Sneeze,0,1894,\N,1,"Documentary,Short",5.4,1667,NaN

In [11]:
for i in range(0,len(movies)) :
  v = movies.numVotes[i]
  m = np.percentile(movies.averageRating, q = .10)
  C = movies['averageRating'].mean()
  R = movies.averageRating[i]
  movies.WeightedRating[i] = (v/(v+m) * R) + (m/(m+v) * C)

C:\Users\Abbie\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [12]:
movies.head()

,titleId,ordering,title,region,language,types,attributes,isOriginalTitle,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres,averageRating,numVotes,WeightedRating
0,tt0000001,5,Carmencita,\N,\N,original,\N,1,tt0000001,short,Carmencita,Carmencita,0,1894,\N,1,"Documentary,Short",5.6,1550,5.600761
1,tt0000003,4,Pauvre Pierrot,\N,\N,original,\N,1,tt0000003,short,Pauvre Pierrot,Pauvre Pierrot,0,1892,\N,4,"Animation,Comedy,Romance",6.5,1207,6.499860
2,tt0000005,8,Blacksmith Scene,\N,\N,original,\N,1,tt0000005,short,Blacksmith Scene,Blacksmith Scene,0,1893,\N,1,"Comedy,Short",6.1,1934,6.100222
3,tt0000007,2,Corbett and Courtney Before the Kinetograph,\N,\N,original,\N,1,tt0000007,short,Corbett and Courtney Before the Kinetograph,Corbett and Courtney Before the Kinetograph,0,1894,\N,1,"Short,Sport",5.5,615,5.502158
4,tt0000008,4,Edison Kinetoscopic Record of a Sneeze,\N,\N,original,\N,1,tt0000008,short,Edison Kinetoscopic Record of a Sneeze,Edison Kinetoscopic Record of a Sneeze,0,1894,\N,1,"Documentary,Short",5.4,1667,5.400887

In [13]:
def recommend(genrechoice, typechoice, agechoice = 0):
  PossMovie = movies[movies['genres'].str.contains(genrechoice)]
  PossMovie = PossMovie[PossMovie['titleType'].str.contains(typechoice)]
  if (agechoice == "Old" or agechoice == 'old' or agechoice == "OLD"):
    PossMovie = PossMovie[PossMovie.startYear <= 2000]
  if (agechoice == "New" or agechoice == 'new' or agechoice == "NEW"):
    PossMovie = PossMovie[PossMovie.startYear > 2000]
  else: 
    PossMovie = PossMovie
  Ordered = PossMovie.sort_values(by="WeightedRating", ascending = False) 
  Ordered = Ordered[['title', 'genres', 'titleType', 'startYear', 'WeightedRating']]
  Top5 = Ordered[:5]
  return Top5

In [14]:
recommend('Comedy', 'movie', 'New')

,title,genres,titleType,startYear,WeightedRating
45122,Shibu,Comedy,movie,2019,9.391544
59808,CM101MMXI Fundamentals,"Comedy,Documentary",movie,2013,9.199900
67251,The Weight of Chains 2,"Comedy,Documentary,History",movie,2014,8.996412
75873,10 Days Before the Wedding,"Comedy,Drama,Musical",movie,2018,8.890196
34554,Anbe Sivam,"Adventure,Comedy,Drama",movie,2003,8.799735